#!/usr/bin/env python3
"""
Run the complete automated reproduction pipeline for the AgentArena / WormShield paper.

Place this file in the same folder as:
    wormshield_learned_payload.py
    wormshield_tune_threshold.py
    wormshield_low_fpr_eval.py
    donkeyrail_agentarena.py
    wormshield_leave_one_task_out.py
    wormshield_run_bootstrap_ci.py
    wormshield_semantic_relation_ablation.py
    wormshield_transformation_robustness_agentarena.py
    wormshieldClasifierAblation.py
    threshold_sensivity.py
    plot_wormshield.py
    agentarena_containment_replay.py
    plot_containment_relays.py
    size_analize.py
    error_analise.py
    wormshield-observable-main.csv
    donkeyrail-test/

Recommended clean run:
    python reproduce_all.py --fresh

Optional:
    python reproduce_all.py --fresh --install-missing
    python reproduce_all.py --skip-bootstrap
    python reproduce_all.py --reuse-features

What this script does:
    1. Checks the input dataset and expected paper counts.
    2. Optionally removes generated result folders.
    3. Runs the main WormShield training/testing/ablation on AgentArena and AI-Worm.
    4. Tunes the AgentArena operating threshold by validation F1.
    5. Selects the AI-Worm operating threshold from validation data under a 3% FPR budget.
    6. Runs matched-split DonkeyRail baselines on AgentArena.
    7. Runs leave-one-task-family-out evaluation.
    8. Runs semantic-relation ablation.
    9. Runs classifier-head ablation.
    10. Runs clustered bootstrap confidence intervals.
    11. Runs propagation-style robustness analysis.
    12. Runs threshold-sensitivity analysis.
    13. Generates ROC figures.
    14. Runs offline counterfactual containment replay.
    15. Generates the relay-only containment figure.
    16. Runs network-size and topology threat-scaling analysis.
    17. Runs error analysis.
    18. Writes one timestamped log file per step and a summary JSON.

Not automated here:
    - Manual 45-case oracle validation, because the human labels must be supplied manually.
    - The AI-Worm DonkeyRail rows that the paper explicitly takes from the original
      DonkeyRail evaluation notebook. Those are not generated by the Python scripts
      in this cleaned folder.
"""

from __future__ import annotations

import argparse
import importlib
import json
import os
import shutil
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parent
PYTHON = sys.executable

EXPECTED_ROWS = 1623
EXPECTED_RUNS = 621
EXPECTED_LABELS = {
    "clean": 819,
    "exposed": 331,
    "propagating": 473,
}
EXPECTED_BINARY = {
    0: 1150,
    1: 473,
}

SCRIPT_CANDIDATES = {
    "main": [
        "wormshield_learned_payload.py",
    ],
    "threshold_tuning": [
        "wormshield_tune_threshold.py",
    ],
    "low_fpr": [
        "wormshield_low_fpr_eval.py",
    ],
    "donkeyrail": [
        "donkeyrail_agentarena.py",
    ],
    "leave_one_task": [
        "wormshield_leave_one_task_out.py",
    ],
    "bootstrap": [
        "wormshield_run_bootstrap_ci.py",
    ],
    "semantic_relation": [
        "wormshield_semantic_relation_ablation.py",
    ],
    "transformation": [
        "wormshield_transformation_robustness_agentarena.py",
        "wormshield_propagation_style_robustness_agentarena.py",
        "wormshield_transformation_robustness_w.py",
    ],
    "classifier": [
        "wormshieldClasifierAblation.py",
        "wormshield_classifier_ablation.py",
    ],
    "threshold_sensitivity": [
        "threshold_sensivity.py",
        "threshold_sensitivity.py",
    ],
    "roc": [
        "plot_wormshield.py",
        "plot_wormshield_roc.py",
    ],
    "containment": [
        "agentarena_containment_replay.py",
    ],
    "containment_plot": [
        "plot_containment_relays.py",
    ],
    "size_topology": [
        "size_analize.py",
        "agentarena_threat_scaling_analysis.py",
    ],
    "error_analysis": [
        "error_analise.py",
        "wormshield_error_analysis.py",
    ],
}

GENERATED_DIRS = [
    "WormShield_Learned_Payload_Results",
    "DonkeyRail_AgentArena_Matched_Splits_Results",
    "WormShield_Leave_One_Task_Out",
    "WormShield_Run_Bootstrap_CI",
    "WormShield_Semantic_Relation_Ablation",
    "AgentArena_Containment_Replay_Results",
    "AgentArena_Threat_Scaling_Results",
]

DEPENDENCIES = {
    "pandas": "pandas",
    "numpy": "numpy",
    "sklearn": "scikit-learn",
    "xgboost": "xgboost",
    "joblib": "joblib",
    "torch": "torch",
    "transformers": "transformers",
    "sentencepiece": "sentencepiece",
    "nltk": "nltk",
    "rouge_score": "rouge-score",
    "matplotlib": "matplotlib",
}

AIWORM_REQUIRED = [
    Path("donkeyrail-test")
    / "Here-Comes-the-AI-Worm-master"
    / "DonkeyRail"
    / "Training_Samples"
    / "Experiment_Results_Benign.csv",
    Path("donkeyrail-test")
    / "Here-Comes-the-AI-Worm-master"
    / "DonkeyRail"
    / "Training_Samples"
    / "Experiment_Results_Virus.csv",
    Path("donkeyrail-test")
    / "Here-Comes-the-AI-Worm-master"
    / "DonkeyRail"
    / "Testing_Samples"
    / "Benign100130.csv",
    Path("donkeyrail-test")
    / "Here-Comes-the-AI-Worm-master"
    / "DonkeyRail"
    / "Testing_Samples"
    / "Phishing.csv",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run all automated paper reproduction experiments."
    )
    parser.add_argument(
        "--fresh",
        action="store_true",
        help="Delete generated result folders before running.",
    )
    parser.add_argument(
        "--reuse-features",
        action="store_true",
        help=(
            "Do not force reconstruction of the main transformer feature cache. "
            "For a strict reproduction run, leave this off."
        ),
    )
    parser.add_argument(
        "--install-missing",
        action="store_true",
        help="Install missing Python packages using the current Python interpreter.",
    )
    parser.add_argument(
        "--skip-bootstrap",
        action="store_true",
        help="Skip the 5000-replicate clustered bootstrap step.",
    )
    parser.add_argument(
        "--continue-on-error",
        action="store_true",
        help="Continue later steps after a failed step.",
    )
    parser.add_argument(
        "--allow-dataset-mismatch",
        action="store_true",
        help="Continue even if the CSV counts do not match the current paper.",
    )
    return parser.parse_args()


def banner(text: str) -> None:
    print("\n" + "=" * 100)
    print(text)
    print("=" * 100)


def resolve_script(key: str) -> Path:
    for name in SCRIPT_CANDIDATES[key]:
        p = ROOT / name
        if p.exists():
            return p

    if key == "transformation":
        matches = sorted(ROOT.glob("wormshield*transformation*robustness*.py"))
        if matches:
            return matches[0]

    raise FileNotFoundError(
        f"Could not find script for '{key}'. Tried: "
        + ", ".join(SCRIPT_CANDIDATES[key])
    )


def check_python_version() -> None:
    if sys.version_info < (3, 10):
        raise RuntimeError(
            f"Python 3.10+ is required. Current version: {sys.version}"
        )


def missing_dependencies() -> list[tuple[str, str]]:
    missing = []
    for module_name, package_name in DEPENDENCIES.items():
        try:
            importlib.import_module(module_name)
        except Exception:
            missing.append((module_name, package_name))
    return missing


def install_dependencies(missing: list[tuple[str, str]]) -> None:
    packages = sorted({package for _, package in missing})
    if not packages:
        return
    print("Installing missing packages:")
    print("  " + " ".join(packages))
    subprocess.run(
        [PYTHON, "-m", "pip", "install", *packages],
        cwd=ROOT,
        check=True,
    )


def validate_required_inputs() -> dict[str, str]:
    required_root_files = [
        ROOT / "wormshield-observable-main.csv",
        ROOT / "wormshield_learned_payload.py",
    ]

    for p in required_root_files:
        if not p.exists():
            raise FileNotFoundError(f"Missing required input: {p.name}")

    for rel in AIWORM_REQUIRED:
        p = ROOT / rel
        if not p.exists():
            raise FileNotFoundError(
                "Missing AI-Worm benchmark file:\n"
                f"  {p}\n"
                "Check the donkeyrail-test folder structure."
            )

    resolved = {}
    for key in SCRIPT_CANDIDATES:
        resolved[key] = str(resolve_script(key).name)

    containment_path = resolve_script("containment")
    containment_text = containment_path.read_text(
        encoding="utf-8",
        errors="ignore",
    )
    required_markers = [
        "run_metrics.csv",
        "containment_table.csv",
        "replay_audit.csv",
    ]
    missing_markers = [
        marker
        for marker in required_markers
        if marker not in containment_text
    ]
    if missing_markers:
        raise RuntimeError(
            f"{containment_path.name} does not look like the full replay script. "
            f"Missing markers: {missing_markers}. "
            "Use the full v3 containment replay file."
        )

    return resolved


def audit_dataset(log_dir: Path, allow_mismatch: bool) -> dict:
    import pandas as pd

    path = ROOT / "wormshield-observable-main.csv"
    df = pd.read_csv(path)

    required_columns = {
        "run_id",
        "label_binary",
        "label_multiclass",
    }
    missing_columns = sorted(required_columns.difference(df.columns))
    if missing_columns:
        raise ValueError(
            f"Dataset is missing required columns: {missing_columns}"
        )

    label_counts = (
        df["label_multiclass"]
        .fillna("")
        .astype(str)
        .str.strip()
        .str.lower()
        .value_counts()
        .to_dict()
    )

    binary_counts = (
        pd.to_numeric(
            df["label_binary"],
            errors="raise",
        )
        .astype(int)
        .value_counts()
        .sort_index()
        .to_dict()
    )

    audit = {
        "dataset": str(path),
        "rows": int(len(df)),
        "unique_runs": int(df["run_id"].astype(str).nunique()),
        "label_multiclass_counts": {
            str(k): int(v)
            for k, v in label_counts.items()
        },
        "label_binary_counts": {
            str(k): int(v)
            for k, v in binary_counts.items()
        },
        "expected": {
            "rows": EXPECTED_ROWS,
            "unique_runs": EXPECTED_RUNS,
            "label_multiclass_counts": EXPECTED_LABELS,
            "label_binary_counts": {
                str(k): v
                for k, v in EXPECTED_BINARY.items()
            },
        },
    }

    problems = []

    if len(df) != EXPECTED_ROWS:
        problems.append(
            f"rows={len(df)} expected={EXPECTED_ROWS}"
        )

    run_count = int(df["run_id"].astype(str).nunique())
    if run_count != EXPECTED_RUNS:
        problems.append(
            f"runs={run_count} expected={EXPECTED_RUNS}"
        )

    for label, expected in EXPECTED_LABELS.items():
        actual = int(label_counts.get(label, 0))
        if actual != expected:
            problems.append(
                f"{label}={actual} expected={expected}"
            )

    for label, expected in EXPECTED_BINARY.items():
        actual = int(binary_counts.get(label, 0))
        if actual != expected:
            problems.append(
                f"binary_{label}={actual} expected={expected}"
            )

    audit["matches_current_paper"] = not problems
    audit["problems"] = problems

    audit_path = log_dir / "dataset_audit.json"
    audit_path.write_text(
        json.dumps(audit, indent=2),
        encoding="utf-8",
    )

    print("\nDataset audit:")
    print(f"  rows: {audit['rows']}")
    print(f"  runs: {audit['unique_runs']}")
    print(f"  labels: {audit['label_multiclass_counts']}")
    print(f"  binary: {audit['label_binary_counts']}")

    if problems:
        print("\nDataset does not match the current paper:")
        for problem in problems:
            print(f"  {problem}")

        if not allow_mismatch:
            raise RuntimeError(
                "Dataset audit failed. "
                "Use --allow-dataset-mismatch only if this difference is intentional."
            )
    else:
        print("  status: matches current paper counts")

    return audit


def clean_generated_dirs() -> list[str]:
    removed = []
    for name in GENERATED_DIRS:
        p = ROOT / name
        if p.exists():
            print(f"Removing generated folder: {p}")
            shutil.rmtree(p)
            removed.append(name)
    return removed


def ensure_expected(paths: Iterable[Path]) -> list[str]:
    missing = []
    for p in paths:
        if not p.exists():
            missing.append(str(p))
    return missing


def run_step(
    number: int,
    name: str,
    command: list[str],
    log_dir: Path,
    expected_paths: Iterable[Path] = (),
) -> dict:
    banner(f"STEP {number}: {name}")
    print("Command:")
    print("  " + " ".join(f'"{x}"' if " " in x else x for x in command))

    slug = "".join(
        c.lower() if c.isalnum() else "_"
        for c in name
    ).strip("_")
    log_path = log_dir / f"{number:02d}_{slug}.log"

    env = os.environ.copy()
    env["PYTHONUNBUFFERED"] = "1"
    env["PYTHONIOENCODING"] = "utf-8"

    start = time.time()

    with log_path.open("w", encoding="utf-8") as log:
        log.write("COMMAND\n")
        log.write(" ".join(command) + "\n\n")
        log.flush()

        process = subprocess.Popen(
            command,
            cwd=ROOT,
            env=env,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            encoding="utf-8",
            errors="replace",
            bufsize=1,
        )

        assert process.stdout is not None

        for line in process.stdout:
            print(line, end="")
            log.write(line)
            log.flush()

        return_code = process.wait()

    elapsed = time.time() - start

    expected_paths = list(expected_paths)
    missing_outputs = ensure_expected(expected_paths)

    result = {
        "step": number,
        "name": name,
        "command": command,
        "return_code": int(return_code),
        "seconds": round(elapsed, 3),
        "log": str(log_path),
        "expected_outputs": [str(p) for p in expected_paths],
        "missing_expected_outputs": missing_outputs,
        "status": (
            "success"
            if return_code == 0 and not missing_outputs
            else "failed"
        ),
    }

    if return_code != 0:
        print(
            f"\nFAILED: {name} returned code {return_code}. "
            f"See {log_path}"
        )
    elif missing_outputs:
        print("\nFAILED: command completed but expected outputs are missing:")
        for p in missing_outputs:
            print(f"  {p}")
    else:
        print(f"\nCompleted in {elapsed / 60.0:.2f} minutes.")

    return result


def build_steps(args: argparse.Namespace) -> list[dict]:
    main = resolve_script("main")
    threshold = resolve_script("threshold_tuning")
    low_fpr = resolve_script("low_fpr")
    donkey = resolve_script("donkeyrail")
    leave_one = resolve_script("leave_one_task")
    semantic = resolve_script("semantic_relation")
    classifier = resolve_script("classifier")
    bootstrap = resolve_script("bootstrap")
    transformation = resolve_script("transformation")
    threshold_sensitivity = resolve_script("threshold_sensitivity")
    roc = resolve_script("roc")
    containment = resolve_script("containment")
    containment_plot = resolve_script("containment_plot")
    size_topology = resolve_script("size_topology")
    error_analysis = resolve_script("error_analysis")

    main_command = [
        PYTHON,
        str(main),
        "all",
        "--dataset",
        "both",
    ]
    if not args.reuse_features:
        main_command.append("--rebuild-features")

    steps = [
        {
            "name": "Main WormShield train, test, and component ablation",
            "command": main_command,
            "expected": [
                ROOT / "WormShield_Learned_Payload_Results"
                / "main_models"
                / "agentarena_seed_7.joblib",
                ROOT / "WormShield_Learned_Payload_Results"
                / "main_models"
                / "aiworm_seed_7.joblib",
                ROOT / "WormShield_Learned_Payload_Results"
                / "ablation_models"
                / "agentarena"
                / "semantic_plus_learned_payload"
                / "seed_7.joblib",
            ],
        },
        {
            "name": "AgentArena validation-F1 threshold tuning",
            "command": [
                PYTHON,
                str(threshold),
                "--dataset",
                "agentarena",
            ],
            "expected": [
                ROOT / "WormShield_Learned_Payload_Results"
                / "threshold_tuning"
                / "threshold_tuning_summary.csv",
                ROOT / "WormShield_Learned_Payload_Results"
                / "threshold_tuning"
                / "selected_thresholds.csv",
            ],
        },
        {
            "name": "AI-Worm validation low-FPR operating point",
            "command": [
                PYTHON,
                str(low_fpr),
                "--dataset",
                "aiworm",
                "--target-fpr",
                "0.03",
            ],
            "expected": [
                ROOT / "WormShield_Learned_Payload_Results"
                / "low_fpr_evaluation"
                / "low_fpr_summary.csv",
                ROOT / "WormShield_Learned_Payload_Results"
                / "low_fpr_evaluation"
                / "selected_low_fpr_thresholds.csv",
            ],
        },
        {
            "name": "Matched-split DonkeyRail baselines on AgentArena",
            "command": [
                PYTHON,
                str(donkey),
            ],
            "expected": [
                ROOT / "DonkeyRail_AgentArena_Matched_Splits_Results"
                / "donkeyrail_paper_table.csv",
                ROOT / "DonkeyRail_AgentArena_Matched_Splits_Results"
                / "donkeyrail_matched_summary.csv",
            ],
        },
        {
            "name": "Leave-one-task-family-out evaluation",
            "command": [
                PYTHON,
                str(leave_one),
            ],
            "expected": [
                ROOT / "WormShield_Leave_One_Task_Out"
                / "leave_one_task_out_summary.csv",
            ],
        },
        {
            "name": "Explicit semantic-relation ablation",
            "command": [
                PYTHON,
                str(semantic),
            ],
            "expected": [
                ROOT / "WormShield_Semantic_Relation_Ablation"
                / "semantic_relation_summary.csv",
            ],
        },
        {
            "name": "Classifier-head ablation",
            "command": [
                PYTHON,
                str(classifier),
            ],
            "expected": [
                ROOT / "WormShield_Learned_Payload_Results"
                / "classifier_ablation_agentarena"
                / "classifier_ablation_summary.csv",
            ],
        },
    ]

    if not args.skip_bootstrap:
        steps.append(
            {
                "name": "Run-cluster bootstrap confidence intervals",
                "command": [
                    PYTHON,
                    str(bootstrap),
                    "--bootstrap-reps",
                    "5000",
                ],
                "expected": [
                    ROOT / "WormShield_Run_Bootstrap_CI"
                    / "bootstrap_ci_per_seed.csv",
                    ROOT / "WormShield_Run_Bootstrap_CI"
                    / "bootstrap_ci_width_summary.csv",
                ],
            }
        )

    steps.extend(
        [
            {
                "name": "Propagation-style robustness",
                "command": [
                    PYTHON,
                    str(transformation),
                ],
                "expected": [
                    ROOT / "WormShield_Learned_Payload_Results"
                    / "propagation_style_robustness_agentarena"
                    / "propagation_style_summary.csv",
                ],
            },
            {
                "name": "Threshold-sensitivity analysis",
                "command": [
                    PYTHON,
                    str(threshold_sensitivity),
                ],
                "expected": [
                    ROOT / "WormShield_Learned_Payload_Results"
                    / "threshold_sensitivity"
                    / "threshold_sensitivity_summary.csv",
                    ROOT / "WormShield_Learned_Payload_Results"
                    / "threshold_sensitivity"
                    / "threshold_sensitivity.png",
                ],
            },
            {
                "name": "ROC analysis and figures",
                "command": [
                    PYTHON,
                    str(roc),
                ],
                "expected": [
                    ROOT / "WormShield_Learned_Payload_Results"
                    / "figures"
                    / "roc_auc_summary.csv",
                    ROOT / "WormShield_Learned_Payload_Results"
                    / "figures"
                    / "agentarena_roc_large_text.png",
                    ROOT / "WormShield_Learned_Payload_Results"
                    / "figures"
                    / "aiworm_roc_large_text.png",
                ],
            },
            {
                "name": "Offline counterfactual containment replay",
                "command": [
                    PYTHON,
                    str(containment),
                ],
                "expected": [
                    ROOT / "AgentArena_Containment_Replay_Results"
                    / "run_metrics.csv",
                    ROOT / "AgentArena_Containment_Replay_Results"
                    / "containment_table.csv",
                    ROOT / "AgentArena_Containment_Replay_Results"
                    / "replay_audit.csv",
                ],
            },
            {
                "name": "Relay-only containment figure",
                "command": [
                    PYTHON,
                    str(containment_plot),
                ],
                "expected": [
                    ROOT / "AgentArena_Containment_Replay_Results"
                    / "containment_figure_relays_only_counts.png",
                ],
            },
            {
                "name": "Network-size and topology threat scaling",
                "command": [
                    PYTHON,
                    str(size_topology),
                ],
                "expected": [
                    ROOT / "AgentArena_Threat_Scaling_Results"
                    / "threat_by_size_summary.csv",
                    ROOT / "AgentArena_Threat_Scaling_Results"
                    / "threat_by_topology_summary.csv",
                    ROOT / "AgentArena_Threat_Scaling_Results"
                    / "network_size_reach_fraction.png",
                    ROOT / "AgentArena_Threat_Scaling_Results"
                    / "topology_reach_fraction.png",
                ],
            },
            {
                "name": "WormShield error analysis",
                "command": [
                    PYTHON,
                    str(error_analysis),
                ],
                "expected": [
                    ROOT / "WormShield_Learned_Payload_Results"
                    / "error_analysis"
                    / "error_summary_overall.csv",
                    ROOT / "WormShield_Learned_Payload_Results"
                    / "error_analysis"
                    / "subgroup_metrics_summary.csv",
                    ROOT / "WormShield_Learned_Payload_Results"
                    / "error_analysis"
                    / "propagation_style_error_summary.csv",
                ],
            },
        ]
    )

    return steps


def main() -> int:
    args = parse_args()

    banner("AGENTARENA / WORMSHIELD COMPLETE REPRODUCTION")

    check_python_version()

    missing = missing_dependencies()
    if missing:
        print("Missing Python dependencies:")
        for module_name, package_name in missing:
            print(f"  {module_name}  ->  pip package: {package_name}")

        if args.install_missing:
            install_dependencies(missing)
            missing_after = missing_dependencies()
            if missing_after:
                raise RuntimeError(
                    "Some dependencies are still unavailable after installation: "
                    + ", ".join(module for module, _ in missing_after)
                )
        else:
            print(
                "\nInstall them first, or rerun with --install-missing."
            )
            return 2

    resolved_scripts = validate_required_inputs()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_dir = ROOT / "Reproduction_Logs" / timestamp
    log_dir.mkdir(parents=True, exist_ok=True)

    dataset_audit = audit_dataset(
        log_dir,
        allow_mismatch=args.allow_dataset_mismatch,
    )

    removed_dirs = []
    if args.fresh:
        banner("CLEANING GENERATED RESULTS")
        removed_dirs = clean_generated_dirs()

    steps = build_steps(args)

    run_summary = {
        "started_at": datetime.now().isoformat(timespec="seconds"),
        "root": str(ROOT),
        "python": sys.version,
        "python_executable": PYTHON,
        "fresh": bool(args.fresh),
        "reuse_features": bool(args.reuse_features),
        "skip_bootstrap": bool(args.skip_bootstrap),
        "removed_generated_dirs": removed_dirs,
        "resolved_scripts": resolved_scripts,
        "dataset_audit": dataset_audit,
        "manual_oracle_validation_run": False,
        "aiworm_official_donkeyrail_notebook_run": False,
        "steps": [],
    }

    summary_path = log_dir / "summary.json"

    for index, step in enumerate(steps, start=1):
        result = run_step(
            index,
            step["name"],
            step["command"],
            log_dir,
            expected_paths=step["expected"],
        )

        run_summary["steps"].append(result)
        summary_path.write_text(
            json.dumps(run_summary, indent=2),
            encoding="utf-8",
        )

        if result["status"] != "success" and not args.continue_on_error:
            run_summary["finished_at"] = datetime.now().isoformat(
                timespec="seconds"
            )
            run_summary["overall_status"] = "failed"
            summary_path.write_text(
                json.dumps(run_summary, indent=2),
                encoding="utf-8",
            )

            banner("REPRODUCTION STOPPED")
            print(f"Failed step: {result['name']}")
            print(f"Log: {result['log']}")
            print(f"Summary: {summary_path}")
            return 1

    failures = [
        result
        for result in run_summary["steps"]
        if result["status"] != "success"
    ]

    run_summary["finished_at"] = datetime.now().isoformat(
        timespec="seconds"
    )
    run_summary["overall_status"] = (
        "success"
        if not failures
        else "completed_with_failures"
    )

    summary_path.write_text(
        json.dumps(run_summary, indent=2),
        encoding="utf-8",
    )

    banner("REPRODUCTION FINISHED")

    print(f"Overall status: {run_summary['overall_status']}")
    print(f"Run logs: {log_dir}")
    print(f"Summary JSON: {summary_path}")

    print("\nMain result locations:")
    result_locations = [
        ROOT / "WormShield_Learned_Payload_Results",
        ROOT / "DonkeyRail_AgentArena_Matched_Splits_Results",
        ROOT / "WormShield_Leave_One_Task_Out",
        ROOT / "WormShield_Semantic_Relation_Ablation",
        ROOT / "WormShield_Run_Bootstrap_CI",
        ROOT / "AgentArena_Containment_Replay_Results",
        ROOT / "AgentArena_Threat_Scaling_Results",
    ]
    for p in result_locations:
        if p.exists():
            print(f"  {p}")

    print(
        "\nReminder: this runner intentionally does not perform the manual "
        "45-case oracle validation or the original DonkeyRail AI-Worm "
        "notebook evaluation."
    )

    return 0 if not failures else 1


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        print("\nInterrupted by user.")
        raise SystemExit(130)
    except Exception as exc:
        print("\nFATAL ERROR")
        print(type(exc).__name__ + ": " + str(exc))
        raise
